SRCS=RealTimePlayer.cpp \
     RealTimePlayerAudio.cpp \
     RealTimePlayerVideo.cpp

LIB=realtimeplayer.a

include ../../../Makefile.include
-include $(patsubst %.cpp,%.P,$(patsubst %.c,%.P,$(SRCS)))
